### ISSUE TITLE
Extend metadata.json with commit/branch/tag field

### ISSUE THREAD

**Issue by CasperWA** [aiidalab/aiidalab#60] opened 2020-05-20 12:39 UTC
It would be extremely useful for my OPTIMADE Client app to be able to direct the AiiDA lab app store to install a specific commit/branch/tag as the default, instead of my repository's default branch on GitHub.

I would imagine this to be a very useful feature for other applications as well, e.g., in order to more easily have the distinction of keeping GitHub for developers/developing and AiiDA lab for stable releases.
As it is now, AiiDA lab will install the application using the default branch and then one can change this after the fact, which is not always ideal.
This means that if one want an AiiDA lab app to always work by default, one MUST set keep the default branch on GitHub a stable release branch, which is not desired for development, where one would like the automation of closing issues, i.e., having a develop branch be the default (since this is how GitHub works).

**Comment by CasperWA** [comment] 2020-05-20 13:00
Actually, I guess it would make most sense to put this information _not_ in the `metadata.json`, but rather in the `apps.json` from the [`aiidalab-registry`](https://github.com/aiidalab/aiidalab-registry).

**Comment by CasperWA** [comment] 2020-05-20 13:59
Mentioning @csadorf and @yakutovicha.

This change, or something equivalent, is a necessity for me before I can continue to move the [`aiidalab-optimade`](https://github.com/aiidalab/aiidalab-optimade) repository over to [`materialscloud-org`](https://github.com/materialscloud-org) as discussed with @giovannipizzi.

**Comment by csadorf** [comment] 2020-05-20 15:53
I'd prefer to use URIs to indicate the exact location and potential reference (branch) for this, see my comment on the related PR: https://github.com/aiidalab/aiidalab-registry/pull/43#pullrequestreview-415478785

**Comment by yakutovicha** [comment] 2020-06-16 14:58
The final design:

An app registry entry is defined via a URL that references a git repository that contains an app. The URL must be of the form: <base_url>[@<ref>], where <base_url> must be a URL that points to a valid git repository and <ref> within the optional second part of the URL must be a [git-reference](https://git-scm.com/book/en/v2/Git-Internals-Git-References) that is valid for the referenced git repository.

**Comment by yakutovicha** [comment] 2020-07-29 13:59
I believe the issue is fixed in #80. I am going to close it.

**Closed by yakutovicha** 2020-07-29 14:00 UTC
Labels: enhancement
