### ISSUE TITLE
Error when opening server after startup

### ISSUE THREAD

**Issue by mbercx** [aiidalab/aiidalab#277] opened 2022-05-03 08:32 UTC
I just tried starting a new AiiDAlab server:

```console
$ aiidalab-launch start
Downloading latest version of 'aiidalab/aiidalab-docker-stack:latest'... done.
Recreating container... done.
Starting container... done.
Waiting for AiiDAlab instance to get ready... done.
Unable to detect a web browser which indicates that you might be running
AiiDAlab on a remote machine. If this is the case, consider to create an SSH
tunnel to access AiiDAlab on your local computer. For this, run a command
similar to

  ssh mbercx@theospc46 -NfL 8888:localhost:8888

on your local computer, then open AiiDAlab on your local computer at

  http://localhost:8888/?token=1957c3077cd75519c9adb4c72b884adaa99cefdd3c1fad8c0cb7c07e3aa7fc06

See https://github.com/aiidalab/aiidalab-launch/blob/main/ssh-forward.md for
more detailed instructions on SSH port forwarding.

Home mounted: /home/mbercx/aiidalab -> /home/aiida
```

But when opening the server, I get the following error:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_1675/3712947380.py in <module>
     34     display(update_btn)
     35 else:
---> 36     from home.start_page import AiidaLabHome
     37     home = AiidaLabHome()
     38     if 'move_up' in parsed_url:

/opt/aiidalab-home/home/start_page.py in <module>
     11 from IPython.display import display
     12 
---> 13 from home.utils import load_widget
     14 from home.widgets import AppStatusInfoWidget
     15 

/opt/aiidalab-home/home/utils.py in <module>
      7 import ipywidgets as ipw
      8 from aiidalab.config import AIIDALAB_APPS
----> 9 from markdown import markdown
     10 
     11 

/opt/conda/lib/python3.7/site-packages/markdown/__init__.py in <module>
     27     raise ImportError('A recent version of Python 3 is required.')
     28 
---> 29 from .core import Markdown, markdown, markdownFromFile  # noqa: E402
     30 from .util import PY37                                  # noqa: E402
     31 from .pep562 import Pep562                              # noqa: E402

/opt/conda/lib/python3.7/site-packages/markdown/core.py in <module>
     24 import logging
     25 import importlib
---> 26 from . import util
     27 from .preprocessors import build_preprocessors
     28 from .blockprocessors import build_block_parser

/opt/conda/lib/python3.7/site-packages/markdown/util.py in <module>
     86 
     87 # Only load extension entry_points once.
---> 88 INSTALLED_EXTENSIONS = metadata.entry_points(group='markdown.extensions')
     89 RTL_BIDI_RANGES = (
     90     ('\u0590', '\u07FF'),

TypeError: entry_points() got an unexpected keyword argument 'group'
```

My `aiidalab-launch` version is the latest, I believe:

```console
$ aiidalab-launch version
AiiDAlab Launch v2022.1012
```

Any ideas?

**Comment by csadorf** [comment] 2022-05-05 15:30
@mbercx I am not able to reproduce the issue. I assume that your environment is somehow messed up. Can you try to reset it?

**Comment by csadorf** [comment] 2022-05-06 09:53
@mbercx I will close this for now, but please let us know in case that resetting the environment did not resolve the problem.

**Closed by csadorf** 2022-05-06 09:53 UTC
Labels: question
