### ISSUE TITLE
AiiDAlab apps: Example app for QE bands workflow

### ISSUE THREAD

**Issue by CasperWA** [aiidalab/aiidalab#163] opened 2021-03-22 16:06 UTC
Write an example app to showcase the utilization of AiiDA and QE as an app in AiiDAlab.

The "scaffolding" for this is/has been added in #161.

**Comment by csadorf** [comment] 2021-09-09 15:14
Duplicate of #164 .

**Closed by csadorf** 2021-09-09 15:14 UTC
Labels: documentation
